# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc-8DcPiqM2ezE6Boc8s1ifd1lB_MImB
"""

"""
           Autor:
   Armando Augusto Valladares Uc
   valladaresarmando301@gmail.com
   Version 2.0 : 04/02/2025 05:00

"""
import numpy as np
import matplotlib.pyplot as plt

# Inicializamos epsilon con 1.0 y el contador de iteraciones en 0
epsilon = 1.0
iteracion = 0

N_Iteraciones = []
Epsilon = []

# Bucle para encontrar la precisión de la máquina
while 1.0 + epsilon != 1.0:  # Mientras la suma 1.0 + epsilon sea distinta de 1.0
    epsilon /= 2  # Reducimos epsilon a la mitad
    iteracion += 1  #Incremento del contador por cada iteración
    N_Iteraciones.append(iteracion)  # Guardamos el número de iteración
    Epsilon.append(epsilon)  # Guardamos el valor de epsilon
    print(f"Iteracion: {iteracion}, Precisión de máquina: {epsilon}")  # Mostramos la iteración actual y epsilon

# Grafica
plt.figure()
plt.plot(N_Iteraciones, Epsilon, label='Precisión de máquina', marker='o') #Grafica el valor de epsilon sobre cada iteración
plt.xlabel('Iteracion') #Nombre del eje X
plt.ylabel('Epsilon') #Nombre del eje y
plt.title('Precisión de máquina') #Título de la grafica
plt.show() #Muestra la gráfica en pantalla

epsilon *= 2
print(f"Precisión de máquina: {epsilon}")  # Se imprime la precisión de la máquina obtenida